### ISSUE TITLE
Linter failing in xenial

### ISSUE THREAD

**Issue by pengale** [juju-solutions/layer-apache-flume-kafka#5]
The linter fails in xenial, probably due to the tox.ini not skipping missing interpreters:

```
py34 create: /tmp/tmp5Ii_2J/apache-flume-kafka/.tox/py34
ERROR: InterpreterNotFound: python3.4
____________________________________________________________________________ summary _____________________________________________________________________________
ERROR:   py34: InterpreterNotFound: python3.4
Makefile:12: recipe for target 'lint' failed
make: *** [lint] Error 1
```

I intend to fix this shortly.

**Comment by pengale** [comment]
Issue was just that the charm needed to be rebuilt with up-to-date layers. Published a new charm to ~bigdata-dev. Will publish to the store when I have time to test and make sure that it doesn't break anything ...

**Comment by kwmonroe** [comment]
I recently refreshed all flume charms, and didn't see any lint issues.  Closing out.
